apiVersion: v1
kind: ReplicationController        
metadata:
  name: fb-apache                  
spec:
  replicas: 3                   
  selector:                        
    app: fb-apache              
  template:                        
    metadata:                      
      labels:                      
        app: fb-apache             
    spec:                          
      containers:                  
      - name: fb-apache        
        image: apache:latest        
        ports:                     
        - containerPort: 80
