# blocks - 
---
- name: "exercise to run tasks using blocks"
  hosts: localhost
  gather_facts: no
  tasks:
    - command: "ls /home/ec2-user"
      register: ls_out
      ignore_errors: yes
    - command: "docker ps"
      register: docker_out
      ignore_errors: ture
    - command: "sudo service httpd start"
      register: httpd_start_out


##################

---
- name: exercise to run tasks using blocks
  gather_facts: no
  hosts: localhost
  tasks:
   - block:
      - command: "ls /home/ec2-user"
        register: ls_out
      - command: "docker ps"
        register: docker_out
      - command: "sudo service httpd start"
        register: httpd_start_out
     ignore_errors: true

####################

